version: '3.8'

services:
### MONGO ################################################
  database:
    image: mongo:3.6.8
    container_name: mongodb-local
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    logging:
      driver: none

### MONGO-SEED: LOAD BASE JSON DB ################################################
  database-seed:
      build:
        context: ./database
      links:
        - database
      depends_on:
        - database

### NODEJS ################################################
  backend:
    container_name: backend_walmart
    restart: always
    build:
      context: ./backend
    ports:
      - "${NODE_PORT}:3001"
    links:
      - database
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - database

### ANGULAR ################################################
  frontend:
    container_name: frontend_walmart
    restart: always
    build:
      context: ./frontend
    ports:
      - "${ANGULAR_PORT}:4200"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  