version: '3.8'

services:
  backend:
    container_name: backend_walmart
    restart: always
    build:
      context: ./backend
    ports:
      - "${NODE_PORT}:3001"
    links:
      - database
    volumes:
      - ./backend:/usr/src/app

  database:
    container_name: mongodb-local
    restart: always
    build:
      context: ./database
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    logging:
      driver: none

  frontend:
    container_name: frontend_walmart
    restart: always
    build:
      context: ./frontend
    ports:
      - "${ANGULAR_PORT}:4200"
    volumes:
      - ./frontend:/app

    # volumes:
    #   - ./database:/database
  